In [1]:
import numpy as np

In [10]:
array = np.arange(0,10)

In [11]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array[4]

4

In [15]:
array[5]

5

In [16]:
array2 = np.random.randint(5,20,5)

In [17]:
array2

array([14, 10,  8,  8, 10])

In [18]:
array2[4]

10

In [20]:
array2[:4]

array([14, 10,  8,  8])

In [21]:
array2[:]

array([14, 10,  8,  8, 10])

In [22]:
array2[2:]

array([ 8,  8, 10])

In [24]:
array2[-1]

10

In [25]:
array3 = array2.copy()

In [26]:
array3

array([14, 10,  8,  8, 10])

In [28]:
array3[0] = 2

In [30]:
array3

array([ 2, 10,  8,  8, 10])