In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
array[2,1]

8

In [17]:
array[:,2]

array([3, 6, 9])

In [23]:
array[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])