In [1]:
import numpy as np

In [2]:
array = np.arange(0, 10)

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2 = np.arange(5,15)

In [5]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
array + array2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
array * array2

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [9]:
array - array2

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5])

In [10]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [13]:
np.max(array2)

14

In [14]:
np.min(array2)

5

In [15]:
array +3 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
array2 % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [17]:
array2 / 2

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

In [18]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])