In [1]:
import numpy as np

In [2]:
array = np.arange(0,10)

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
condition = array > 5

In [5]:
condition

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [6]:
array[condition]

array([6, 7, 8, 9])

In [7]:
array2 = array[condition]

In [8]:
array2

array([6, 7, 8, 9])

In [9]:
array3 = array[array > 5]

In [10]:
array3

array([6, 7, 8, 9])

In [11]:
array2 == array3

array([ True,  True,  True,  True])

In [12]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])