In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.88581275, 0.3345727 , 0.75681128, 0.64088496, 0.62586374])

In [3]:
np.random.rand(3,3)

array([[0.27827007, 0.41709661, 0.21366236],
       [0.53980662, 0.47573303, 0.38470858],
       [0.99224322, 0.99307383, 0.42089055]])

In [5]:
np.random.randn(5)

array([-0.77592851,  0.51104154, -0.5117295 , -0.03237376, -0.60730105])

In [6]:
np.random.randn(3,3)

array([[ 0.17481985,  0.76636915, -0.01717164],
       [ 0.37234123, -0.07582872,  0.25542512],
       [ 0.11313182,  1.44383962, -0.0322545 ]])

In [10]:
np.random.random()

0.5631314129124773

In [13]:
np.random.random_sample(5)

array([0.04584752, 0.39137874, 0.86004693, 0.00902028, 0.96024395])

In [14]:
np.random.rand(3,3,3)

array([[[0.71727796, 0.4831779 , 0.85166732],
        [0.53149707, 0.29406227, 0.61929591],
        [0.30344962, 0.44093979, 0.16505666]],

       [[0.15672513, 0.35024574, 0.78932613],
        [0.55194978, 0.94713562, 0.47209845],
        [0.37048467, 0.03165599, 0.76456344]],

       [[0.62282748, 0.53363904, 0.83143751],
        [0.83800442, 0.19130106, 0.89755635],
        [0.08191578, 0.61413032, 0.57612553]]])