In [1]:
import numpy as np

In [2]:
array = np.random.randint(0, 100, 25)

In [3]:
array

array([64, 57,  6, 17, 77, 15, 30, 92, 72, 25, 88, 44, 91, 41, 83, 73, 81,
       89, 39, 40, 11, 64, 23, 41, 30])

In [4]:
matriz = array.reshape(5,5)

In [5]:
matriz

array([[64, 57,  6, 17, 77],
       [15, 30, 92, 72, 25],
       [88, 44, 91, 41, 83],
       [73, 81, 89, 39, 40],
       [11, 64, 23, 41, 30]])

In [6]:
array2 = np.random.randint(25, 72, 21)

In [7]:
array2

array([47, 52, 71, 28, 65, 53, 40, 33, 49, 48, 37, 30, 63, 51, 41, 31, 45,
       40, 33, 44, 69])

In [8]:
matriz2 = array2.reshape(3,7)

In [9]:
matriz2

array([[47, 52, 71, 28, 65, 53, 40],
       [33, 49, 48, 37, 30, 63, 51],
       [41, 31, 45, 40, 33, 44, 69]])