In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [5]:
a1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [8]:
a2 = np.array(a1.reshape(2,2).T)
a2

array([[1, 3],
       [2, 4]])

In [17]:
array1 = [0,1,2,3,4,5,6,7,8,9]
array2 = [10,11,12,13,14,15,16,17,18,19]

In [18]:
array1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
array2

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [20]:
sum(array1 + array2)

190

In [28]:
min(array2)

10

In [23]:
array3 = np.array(array1 + array2)

In [29]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
array3.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
np.array(list(filter(lambda n: n%2==0, array3)))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
array4 = np.random.randint(0, 20, size=20)
array4

array([ 9,  4,  5,  5, 14,  0,  9,  9, 16,  3,  0,  2, 19,  0,  8, 12, 14,
        5, 11,  7])

In [46]:
np.sort(array4)

array([ 0,  4,  4,  5,  5,  6,  9, 10, 10, 11, 12, 12, 12, 12, 14, 16, 16,
       17, 19, 19])

In [55]:
array5 = np.where(array4 % 2 == 0, 1, 0)

In [58]:
array5.reshape(5,4)

array([[1, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])